# Generated by Django 3.0.3 on 2020-08-23 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200823_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
