# Generated by Django 3.0.3 on 2020-09-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200824_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
